SELECT PCPEDC.CODFILIAL,
       SUM(PCPEDC.VLTOTAL)      AS VALORTITULO
FROM PCPEDC
WHERE PCPEDC.DTFAT BETWEEN TO_DATE(:DATAINICIAL, 'DD-MM-YYYY') AND TO_DATE(:DATAFINAL, 'DD-MM-YYYY')
AND PCPEDC.CONDVENDA = 5
GROUP BY PCPEDC.CODFILIAL