SELECT PCPEDC.CODFILIAL,
       SUM(PCPEDC.VLTOTAL) AS VALORTITULO
FROM PCPEDC
WHERE PCPEDC.DTFAT BETWEEN TRUNC(TO_DATE(:DATAINICIAL, 'DD-MM-YYYY'), 'MM') AND TO_DATE(:DATAFINAL, 'DD-MM-YYYY')
AND PCPEDC.CONDVENDA = 5
AND PCPEDC.DTCANCEL IS NULL
GROUP BY PCPEDC.CODFILIAL
