SELECT PCPREST.CODFILIAL,
       CASE
           WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC <= TRUNC(SYSDATE) THEN 'INADIMPLENTE'
           ELSE 'ADIMPLENTE'
           END            AS INADIMPLENCIA,
       SUM(PCPREST.VALOR) AS VALORTITULO
FROM PCPREST
WHERE PCPREST.DTVENC BETWEEN TO_DATE(:DATAINICIAL, 'DD-MM-YYYY') AND TO_DATE(:DATAFINAL, 'DD-MM-YYYY')
  AND (PCPREST.DTPAG IS NULL AND PCPREST.DTVENC <= TRUNC(SYSDATE))
GROUP BY PCPREST.CODFILIAL,
         CASE
             WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC <= TRUNC(SYSDATE) THEN 'INADIMPLENTE'
             ELSE 'ADIMPLENTE'
             END
