SELECT CODFILIAL,
       DTLIBERA,
       EXTRACT(HOUR FROM CAST(DTLIBERA AS TIMESTAMP))  AS HORA_LIBERA,
       TO_CHAR(DATA, 'DD-MM-YYYY')                     AS DATA,
       HORA                                            AS HORA_PEDIDO,
       COUNT(NUMPED)                                   AS QT_PED,
       COUNT(CASE WHEN POSICAO <> 'B' THEN NUMPED END) AS QT_PED_LIB,
       COUNT(CASE WHEN POSICAO = 'B' THEN NUMPED END)  AS QT_PED_BLOQ
FROM (SELECT PCPEDC.CODFILIAL,
             PCPEDC.DTLIBERA,
             PCPEDC.DATA,
             PCPEDC.HORA,
             PCPEDC.MINUTO,
             PCPEDC.POSICAO,
             PCPEDC.NUMPED
      FROM PCPEDC
      WHERE (PCPEDC.POSICAO = 'B' OR (PCPEDC.POSICAO <> 'B' AND PCPEDC.CODFUNCLIBERA IS NOT NULL))
        AND PCPEDC.DATA BETWEEN TO_DATE(:DATAINICIAL, 'DD-MM-YYYY') AND TO_DATE(:DATAFINAL, 'DD-MM-YYYY'))
GROUP BY CODFILIAL, DTLIBERA, DATA, HORA, MINUTO
