SELECT
    /* CABEÇALHO */
    CASE
        WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTBAIXA IS NULL THEN 'ABERTO'
        ELSE 'PAGO'
        END                               AS SITUACAO,
    CASE
        WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE) THEN 'INADIMPLENTE'
        ELSE 'ADIMPLENTE'
        END                               AS INADIMPLENCIA,
    CASE
        WHEN (PCPREST.DTPAG IS NOT NULL AND PCPREST.DTPAG > PCPREST.DTVENC) OR
             (PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE)) THEN 'ATRASO'
        ELSE 'NO PRAZO' END               AS ATRASO,
    PCPREST.CODFILIAL,
    TO_CHAR(PCPREST.DTVENC, 'YYYY-MM-DD') AS DATAVENCIMENTO,
    PCPREST.VALOR                         AS VALORTITULO,
    PCPREST.VPAGO                         AS VALORPAGO,
    PCPREST.TXPERM                        AS VALORJUROS,
    PCPREST.VALORDESC                     AS VALORDESCONTO,
    CASE
        WHEN PCPREST.DTPAG IS NULL AND
             PCPREST.CODCOB NOT IN ('DEVP', 'DEVT', 'BNF', 'BNFT', 'BNFR', 'BNTR', 'BNRP', 'CRED')
            THEN PCPREST.VALOR - NVL(PCPREST.VALORDESC, 0)
        ELSE 0
        END                               AS VALORARECEBER,
    PCPREST.TXPERM                        AS VALORJUROS
FROM PCPREST
WHERE PCPREST.DTVENC BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(TRUNC(SYSDATE, 'MM'))

