SELECT TO_CHAR(PCPREST.DTVENC, 'DD-MM-YYYY') AS DATA,
       PCPREST.CODFILIAL,
       CASE
           WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE) THEN 'INADIMPLENTE'
           ELSE 'ADIMPLENTE'
           END                               AS INADIMPLENCIA,
       SUM(PCPREST.VALOR)                    AS VALORTITULO,
       SUM(PCPREST.VPAGO)                    AS VALORPAGO,
       SUM(PCPREST.TXPERM)                   AS VALORJUROS,
       SUM(PCPREST.VALORDESC)                AS VALORDESCONTO,
       SUM(CASE
               WHEN PCPREST.DTPAG IS NULL AND
                    PCPREST.CODCOB NOT IN ('DEVP', 'DEVT', 'BNF', 'BNFT', 'BNFR', 'BNTR', 'BNRP', 'CRED')
                   THEN PCPREST.VALOR - NVL(PCPREST.VALORDESC, 0)
               ELSE 0
           END)                              AS VALORARECEBER,
       SUM(PCPREST.VLTXBOLETO)               AS VLTXBOLETO
FROM PCPREST
WHERE PCPREST.DTVENC BETWEEN TO_DATE(:DATAINICIAL, 'DD-MM-YYYY') AND TO_DATE(:DATAFINAL, 'DD-MM-YYYY')
GROUP BY PCPREST.DTVENC,
         PCPREST.CODFILIAL,
         CASE
             WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE) THEN 'INADIMPLENTE'
             ELSE 'ADIMPLENTE'
             END
