SELECT
    /* CABEÇALHO */
    CASE
        WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTBAIXA IS NULL THEN 'ABERTO'
        ELSE 'PAGO'
        END                 AS SITUACAO,
    CASE
        WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE) THEN 'INADIMPLENTE'
        ELSE 'ADIMPLENTE'
        END                 AS INADIMPLENCIA,
    CASE
        WHEN (PCPREST.DTPAG IS NOT NULL AND PCPREST.DTPAG > PCPREST.DTVENC) OR
             (PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE)) THEN 'ATRASO'
        ELSE 'NO PRAZO' END AS ATRASO,
    /* CHAVES ESTRANGEIRAS */
    PCPREST.CODFILIAL,
    PCPREST.DTVENC          AS DATAVENCIMENTO,
    /* MEDIDAS */
    PCPREST.VALOR           AS VALORTITULO,
    PCPREST.VPAGO           AS VALORPAGO,
    PCPREST.TXPERM          AS VALORJUROS,
    PCPREST.VALORDESC       AS VALORDESCONTO,
    CASE
        WHEN PCPREST.DTPAG IS NULL AND
             PCPREST.CODCOB NOT IN ('DEVP', 'DEVT', 'BNF', 'BNFT', 'BNFR', 'BNTR', 'BNRP', 'CRED')
            THEN PCPREST.VALOR - NVL(PCPREST.VALORDESC, 0)
        ELSE 0
        END                 AS VALORARECEBER
FROM PCPREST
WHERE 1 = 1
/*
AND PCPREST.CODCOB NOT IN ('DEVP', 'DEVT', 'BNF', 'BNFT', 'BNFR', 'BNTR', 'BNRP')
AND PCPREST.CODCOB NOT IN ('CRED')
*/
--   AND ((PCPREST.DTPAG IS NOT NULL AND PCPREST.DTPAG > PCPREST.DTVENC) OR
--        (PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE)))
--   AND (PCPREST.DTPAG IS NULL AND PCPREST.DTBAIXA IS NULL)

--   AND PCPREST.DTEMISSAO > TO_DATE('01/01/1900', 'DD/MM/YYYY')
AND PCPREST.DTEMISSAO BETWEEN ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1) AND TRUNC(SYSDATE, 'MM') - 1