SELECT PCPEDC.CODFILIAL,
       COUNT(PCPEDC.NUMPED)                                   AS QT_PED,
       COUNT(CASE WHEN PCPEDC.POSICAO <> 'B' THEN PCPEDC.NUMPED END) AS QT_PED_LIB,
       COUNT(CASE WHEN PCPEDC.POSICAO = 'B' THEN PCPEDC.NUMPED END)  AS QT_PED_BLOQ,
       COUNT(CASE WHEN PCMOTBLOQUEIO.TIPO = 1 THEN PCPEDC.NUMPED END)  AS QT_PED_FIN,
       COUNT(CASE WHEN PCMOTBLOQUEIO.TIPO = 2 THEN PCPEDC.NUMPED END)  AS QT_PED_COM,
       COUNT(CASE WHEN PCPEDC.CODMOTIVO IS NULL AND PCPEDC.POSICAO = 'B' THEN PCPEDC.NUMPED END)  AS QT_EM_ANALISE
FROM PCPEDC
LEFT JOIN PCMOTBLOQUEIO ON PCMOTBLOQUEIO.CODMOTIVO = PCPEDC.CODMOTIVO
WHERE (PCPEDC.POSICAO = 'B' OR (PCPEDC.POSICAO <> 'B' AND PCPEDC.CODFUNCLIBERA IS NOT NULL))
  AND PCPEDC.DATA BETWEEN TO_DATE(:DATAINICIAL, 'DD-MM-YYYY') AND TO_DATE(:DATAFINAL, 'DD-MM-YYYY')
GROUP BY PCPEDC.CODFILIAL

